force-app/main/default/objects/DHA_Class__c/DHA_Class__c.object-meta.xml
<CustomObject>
    <label>DHA Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>DHA Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Class_Assignment__c/DHA_Class_Assignment__c.object-meta.xml
<CustomObject>
    <label>DHA Class Assignment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>DHA Class Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Class Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Class_Assignment__c/fields/DHA_Class__c.field-meta.xml
<CustomField>
    <fullName>DHA_Class__c</fullName>
    <label>DHA Class</label>
    <referenceTo>DHA_Class__c</referenceTo>
    <relationshipLabel>DHA Class Assignments</relationshipLabel>
    <relationshipName>DHA_Class_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHA_Class_Assignment__c/fields/DHA_Student__c.field-meta.xml
<CustomField>
    <fullName>DHA_Student__c</fullName>
    <label>DHA Student</label>
    <referenceTo>DHA_Student__c</referenceTo>
    <relationshipLabel>DHA Class Assignments</relationshipLabel>
    <relationshipName>DHA_Class_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHA_Student__c/DHA_Student__c.object-meta.xml
<CustomObject>
    <label>DHA Student</label>
    <nameField>
        <label>DHA Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DHA Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Student__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHA_Student__c/fields/Student_Code__c.field-meta.xml
<CustomField>
    <fullName>Student_Code__c</fullName>
    <displayFormat>ST-{000000}</displayFormat>
    <label>Student Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/DHA_StudentSearchController.cls
public with sharing class DHA_StudentSearchController {
    
    @AuraEnabled
    public static List<DHA_Class_Assignment__c> getStudentsWithConditions(String searchVal, Date birthDate, String className){
        String queryString = 'select DHA_Student__r.Id, DHA_Student__r.Student_Code__c, DHA_Student__r.Name, DHA_Student__r.Birthdate__c, DHA_Student__r.Address__c, DHA_Student__r.Email__c from DHA_Class_Assignment__c';
        List<String> conditions = new List<String>();

        if(searchVal == null && birthDate == null && className == null){
            return Database.query(queryString);
        }

        if(searchVal != null){
            conditions.add('DHA_Student__r.Name like \'%' + searchVal + '%\'');
        }

        if(birthDate != null){
            conditions.add('DHA_Student__r.Birthdate__c=' + birthDate);
        }

        if(className != null){
            conditions.add('DHA_Class__r.Name=\'' + className + '\'');
        }

        queryString += ' where ';
        queryString += string.join(conditions, ' and ');
        List<DHA_Class_Assignment__c> result = Database.query(queryString);

        return result;
    }

    @AuraEnabled
    public static List<DHA_Class__c> getClasses(){          
        List<DHA_Class__c> result = [
                select Name
                from DHA_Class__c
            ];
        
        return result;
    }
}