force-app/main/default/objects/DHA_Management_Setting__c/DHA_Management_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations for DHA Student Management App</description>
    <label>DHA Management Setting</label>
</CustomObject>

force-app/main/default/objects/DHA_Management_Setting__c/fields/Pass_Score__c.field-meta.xml
<CustomField>
    <fullName>Pass_Score__c</fullName>
    <label>Pass Score</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/DHA_Study_Result__c.object-meta.xml
<CustomObject>
    <label>DHA Study Result</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>DHA Study Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Study Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/fields/Final_Score__c.field-meta.xml
<CustomField>
    <fullName>Final_Score__c</fullName>
    <formula>(Score_1__c +  Score_2__c +  Score_3__c ) / 3</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Is_Lastest__c.field-meta.xml
<CustomField>
    <fullName>Is_Lastest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lastest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>NotPassed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHA_BatchProcess.cls
public with sharing class DHA_BatchProcess implements Database.Batchable<SObject>, Database.stateful {
    private Integer numOfUpdated = 0;

    public Database.QueryLocator start(Database.BatchableContext bc){
        Decimal defaultPassScore = DHA_Management_Setting__c.getInstance(UserInfo.getUserId()).Pass_Score__c;
        
        String queryString = 'select Name, Result__c from DHA_Study_Result__c where Is_Lastest__c = true and Final_Score__c > :defaultPassScore';

        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext bc, List<DHA_Study_Result__c> records){
        if(!records.isEmpty()){
            for(DHA_Study_Result__c result : records){
                result.Result__c = 'Passed';
                numOfUpdated += 1;
            }
            update records;
        }
    }

    public void finish(Database.BatchableContext bc){
        system.debug(
            string.format(
                'There are {0} updated study result(s) in the batch process.', 
                new string[]{string.valueOf(numOfUpdated)}
            )
        );
    }
}